export const GET_EVENTS_REQUEST = 'GET_EVENTS_REQUEST'
export const GET_EVENTS_SUCCESS = 'GET_EVENTS_SUCCESS'
export const CREATE_EVENT = 'CREATE_EVENT'
export const GET_EVENTS_FAIL = 'GET_EVENTS_FAIL'

export const GET_EVENTDETAILS_REQUEST = 'GET_EVENTDETAILS_REQUEST'
export const GET_EVENTDETAILS_SUCCESS = 'GET_EVENTDETAILS_SUCCESS'
export const GET_EVENTDETAILS_FAIL = 'GET_EVENTDETAILSS_FAIL'


